ImageMagick導入
arsaga-partners/laravel-alpine pull request #5
Opened 2018-02-13 10:02 UTC by akahorisoh

## Content
ImageMagickを導入

2018-02-13 10:26 UTC, moriya-snj requested changes

2018-02-13 10:26 UTC, moriya-snj commented on Dockerfile
> +    && apk del autoconf g++ libtool make pcre-dev
これ付けてる理由は何ですか？
理解できなくもないけど、g++とかmakeとかまで消してのちに影響しない？

2018-02-14 10:26 UTC, akahorisoh commented
影響が出る可能性がある為
delを削除

2018-02-14 10:57 UTC, moriya-snj approved these changes

2018-02-14 10:57 UTC, merged